### ISSUE TITLE
关于软件开发的一些问题

### ISSUE THREAD

**Issue by rowthan** [zhigui/Enjoy-Music-Player-locales#18]
一次偶然机会装上了这个应用，出乎意料的好用。
意味的发现居然可以脱离浏览器使用，因为一直在做chrome扩展开发，之前从来没注意到还有这个东西。
准备学习一下app开发，这个程序有打算开源吗？或者哪儿有关于app开发的API吗？（大多是关于extension的，似乎chromium也不怎么推广app开发了？）

**Comment by zhigui** [comment]
Chrome 已经不再推荐 package app 的开发了，后续也将无法发布到应用商店，你可以尝试  Electron 或者 NW.js.
