### ISSUE TITLE
功能优化的一点建议

### ISSUE THREAD

**Issue by rowthan** [zhigui/Enjoy-Music-Player-locales#19]
- 关闭程序，能不能做成最小化到“图标管理”那里，类似于QQ那样的做法。

因为很多时候关闭窗口其实并不像退出程序，而是想要最小化，并且不要出现再任务栏里面（我记得很久以前效果就是像QQ那样，不知道是操作系统升级的原因还是享乐升级的原因）。

- 使用网易云api?
我在不适用代理的情况下，在线音乐是更新不到数据的，我猜音乐的来源应该是国外吧，这就使得大多数国内用户是使用不了该部分的功能的，所以有没有想过音乐使用网易云音乐的API呢？

**Comment by zhigui** [comment]
- api 不支持
- 在某个大版本后已经不再支持国内的音乐网站，并且我们超过 90% 的用户为国外用户。
